cluster: qsub -W group_list={cluster.proj} -A {cluster.proj} -l nodes=1:ppn={cluster.core},mem={cluster.vmem},walltime={cluster.time} -e logs/{jobid}_snakemake.err -o logs/{jobid}_snakemake.log
cluster-config: profile_argfinder/cluster_computerome.json
use-conda: True
restart-times: 0
latency-wait: 200
jobs: 200
keep-going: True
