name: argfinder
channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - enabrowsertools=1.5.4
  - fastp=0.23.4
  - kma=1.4.9
  - mash=2.3
  - r-essentials=4.2	
  - samtools=1.17	
  - spades=3.15.5
  - fqgrep=1.0.3
