name: argfinder
channels:
 - conda-forge
 - bioconda
 - default
 - genomicepidemiology
dependencies:
 - snakemake=7.30.1
 - fastp=0.23.4
 - kma=1.4.9
 - mash=2.3
 - r-optparse=1.7.3
 - r-essentials=4.2
 - samtools=1.17
 - spades=3.13.1
 - fqgrep=0.0.3
