name: argprofiler
channels:
  - default
  - conda-forge
  - bioconda
  - genomicepidemiology
dependencies:
  - snakemake>=7.30.1
  - python=3.11
  - fastp=0.23.4
  - kma=1.4.9
  - mash=2.3
  - r-optparse=1.7.3
  - r-essentials=4.2
  - sra-tools>=3.0.1
  - samtools=1.17
  - spades=3.15.5
  - fqgrep=0.0.3
  - fastq-dl=2.0.4
